services:
  db:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "ttmobile"
      MYSQL_PASSWORD: "ttmobile"
      MYSQL_ROOT_PASSWORD: "ttmobile"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

volumes:
  my-db:
  postgres_data:
