version: "3"
services:
  db:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'ttmobile'
      MYSQL_PASSWORD: 'ttmobile'
      MYSQL_ROOT_PASSWORD: 'ttmobile'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

volumes:
  my-db:
